language: node_js
node_js:
  - 16

services:
  - docker

script:
  docker build -t udagram-frontend ./udagram-frontend
  
  docker tag udagram-frontend quyendd2405/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quyendd2405/udagram-frontend:v1
