language: node_js
node_js:
  - 16

services:
  - docker

script:
  ## For build process
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  ## For tag process
  - docker tag udagram-api-feed quyendd2405/udagram-api-feed:v1
  - docker tag udagram-api-user quyendd2405/udagram-api-user:v1
  - docker tag udagram-frontend quyendd2405/udagram-frontend:v2
  - docker tag reverseproxy quyendd2405/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quyendd2405/udagram-api-feed:v1
  - docker push quyendd2405/udagram-api-user:v1
  - docker push quyendd2405/udagram-frontend:v2
  - docker push quyendd2405/reverseproxy:v1
